### ISSUE TITLE
Breaks with`sidescrolloff` and overrides global-only options

### ISSUE THREAD

**Issue by dosentmatter** [kamykn/popup-menu.nvim#3]
I'm using the popup menu with spelunker.vim along with https://github.com/tpope/vim-sensible. I narrowed the issue down to [`sidescrolloff` being set](https://github.com/tpope/vim-sensible/blob/2d9f34c09f548ed4df213389caa2882bfe56db58/plugin/sensible.vim#L45-L47), which causes the suggestions to sidescroll:

![image](https://user-images.githubusercontent.com/5732253/83488672-138d5080-a462-11ea-9318-60c7db58018d.png)

I see you are doing [`setlocal scrolloff=0` in your code](https://github.com/kamykn/popup-menu.nvim/blob/a7ff01ff2f5e97d035666e1b0327ebb5f4c4dea8/autoload/popup_menu.vim#L78) and the same thing can be done with `setlocal sidescrolloff=0`.

However, I don't think `setlocal` is working as you expect. The option is not set local to the popup menu and persist after the menu is closed. The docs say:

```
:setl[ocal] ...		Like ":set" but set only the value local to the
			current buffer or window.  Not all options have a
			local value.  If the option does not have a local
			value the global value is set.
```

The important part is "If the option does not have a local value the global value is set."

Both `scrolloff` and `sidescrolloff` are global-only options.

```
						*'scrolloff'* *'so'*
'scrolloff' 'so'	number	(default 0)
			global
						*'sidescrolloff'* *'siso'*
'sidescrolloff' 'siso'	number (default 0)
			global
```

I guess you can maybe save the previous value of `scrolloff` and then change it back when the menu is about to close? I made a PR #4 doing this.

I'm not sure why other floating windows in neovim don't have this problem though. They also allow `CTRL+N` (down) and `CTRL+P` (up) to navigate the menu. I think the preview window used by https://github.com/neoclide/coc.nvim uses https://github.com/neovim/neovim/pull/6619. I'm not sure if that's different than your implementation.

**Comment by kamykn** [comment]
Hi, @dosentmatter 
Thank you for your Pull Request!

> They also allow CTRL+N (down) and CTRL+P (up) to navigate the menu. 

This is because Select behavior uses the default operation of [tui-go](https://github.com/marcusolsson/tui-go).
And, it is same operation as popup-menu on Vim8.
I'm wondering if I should add the `Ctrl-p` and `Ctrl-n` commands, since the purpose is to provide the similar function as Vim8🤔

**Comment by dosentmatter** [comment]
@kamykn, thanks for merging my PR!

It seems like you are using tui-go [here](https://github.com/kamykn/popup-menu.nvim/blob/master/tui-select/tui-select.go)? Did you just override the default?

In addition to CTRL+N and CTRL+P, I think neovim and vim8 has Tab (down) and SHIFT+Tab (up).

I guess it would be nice to make it match vim defaults. But I am not opposed to the current functionality, which allows using `j` (down) and `k` (up) so I don't have to move my hand over to the arrow keys.

**Comment by kamykn** [comment]
Hi, @dosentmatter.
I've added a new key to move the selector.

Move up: CTRL+P,  SHIFT-TAB
Move down: CTRL+N TAB

Please check it out👍

**Comment by dosentmatter** [comment]
@kamykn, thanks for the update. All the new key bindings are working well!
